nameOverride: ""
fullnameOverride: ""

image:
  repository: rayproject/ray
  tag: "2.9.3"
  pullPolicy: IfNotPresent

command: ["ray", "start", "--head", "--port=6379", "--dashboard-host=0.0.0.0"]
args: ["--block"]

serviceAccount:
  create: true
  annotations: {}
  name: ""

podSecurityContext: {}
securityContext: {}

# Add default service configuration for test-connection.yaml
service:
  type: ClusterIP
  port: 8265  # Using the head node's port as default

head:
  enabled: true
  replicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  service:
    type: ClusterIP
    port: 8265
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi

worker:
  enabled: true
  replicas: 3
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  persistence:
    enabled: true
    storageClass: ""
    size: 10Gi

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: ray.local
      paths:
        - path: /
          pathType: Prefix

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: ray123

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

networkPolicy:
  enabled: false 